### PR TITLE
Allow arbitrary properties to be added to logger options (as per bunyan)

### PR DESCRIPTION
**Pull request by peitschie**
Hello! Firstly, thanks for this project... it's just what I'm looking for.
This PR is purely to make a few type improvements to expose the logging interfaces a bit more widely, and correct the logger options on child loggers.

Please let me know if there's any further adjustments you'd like.

### CODE REVIEW

**Comment by peitschie** [comment]
It'd be great to get #56 merged too, if possible!

**Comment by philmander** [comment]
Hi @peitschie. I have finally had some time to do some maintenance on browser bunyan. I have merged in two prior PRs related to typings. It would be a great help if you could update your PR given these changes.

**Comment by peitschie** [comment]
Done! This patch has reduced down to just exporting a few more interfaces and types I found useful 🙂

Thanks for this @philmander

**Comment by philmander** [comment]
This is now release in `v1.7.0`

**Comment by peitschie** [comment]
Many thanks @philmander 🍻

**Pull request merged**
